# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#

# Title and description of your site
title:        'Simplicity'
description:  'Simplicity is a fast and easy to use jekyll theme for minimalists concentrating on elegance and flexibility.'


# Build settings
url:          'http://phlow.github.io/simplicity'
baseurl:      ''
urlimg:       'http://phlow.github.io/simplicity/images/'
markdown:     kramdown
highlighter:  pygments
permalink:    /:categories/:title/
encoding:     utf-8

# Use <!--more--> in your posts to generate an excerpt and a teaser
excerpt_separator: <!--more-->


gems:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate


# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ['<!-- ', ' -->']
  endings: all
  profile: false
  ignore:
    envs: [development]



#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: page      # Set default layout to page
      show_meta: false  # Hide metadata for all pages
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: page      # Set default layout to page
      show_meta: true   # Show metadata for all posts
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for posts


#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_site_verification:  'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
# bing_webmastertools_id:  ''
# alexa_verify_id:         ''



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments

# disqus_shortname:


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/_4_footer_scripts

# google_analytics_tracking_id: 



#    _____            _       __   __  ___         ___
#   / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#   \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#  ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
# /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
# If you have social media-profiles put your username here.
# Facebook and Twitter will be used in includes/_1_head.html
# To inject some meta-data.

socialmedia:
    youtube: PhlowMedia
    github: phlow
    twitter: phlow
    # facebook: phlow.media
    # soundcloud: phlow
    # tumblr: motizen
    # instagram: phlowmedia
    # rss: # Full URL needed


#     __
#    / /   ____ _____  ____ ___  ______ _____ ____
#   / /   / __ `/ __ \/ __ `/ / / / __ `/ __ `/ _ \
#  / /___/ /_/ / / / / /_/ / /_/ / /_/ / /_/ /  __/
# /_____/\__,_/_/ /_/\__, /\__,_/\__,_/\__, /\___/
#                   /____/            /____/
#
# To translate *Simplicity* just edit the following data.
# The theme uses for example {{ site.language.read_more }} in
# the layout templates to fill in the according information
# given beneath.

language:
    html_language:            'en'      # The language setting is used in /includes/header.html for html-settings
    read_more:                'Read more ›'
    show_all_articles:        'Show All Articles ›'
    visit_frontpage:          'Visit the frontpage'
    comments_headline:        'Comments'
    enable_disqus:            'Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>'
    search:                   'Search'
    search_input_placeholder: 'Search [Hit Tab and start writing]'
    written_by:               'Written by'
    more_articles:            'More Articles'
    follow_me_on:                'Follow me at'
    # More on Accesskeys › http://www.cs.tut.fi/~jkorpela/forms/accesskey.html
    navigation_search:        'Press Accesskey [4] for Search'
    navigation_menu:          'Press Accesskey [6] for Navigation Menu'
    navigation_home:          'Press Accesskey [1] for Homepage'
    subscribe_to_my_rss_feed: 'Subscribe to my RSS Feed'